version: '3.9'

services:
  #  Neo4j
  db:
    image: neo4j:community
    container_name: connected-db
    restart: always
    environment:
      NEO4J_AUTH: neo4j/connected_password
    ports:
      - "7474:7474" # Interface web Neo4j
      - "7687:7687" # Bolt protocol
    volumes:
      - neo4j_data:/data
      - ./database/csv:/var/lib/neo4j/import
      - ./database/init:/scripts
    healthcheck:
      test: [ "CMD-SHELL", "cypher-shell -u neo4j -p connected_password 'RETURN 1'" ]
      interval: 10s
      timeout: 10s
      retries: 5

  db-init:
    image: neo4j:community
    container_name: connected-db-init
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./database/init:/scripts
      - ./database/csv:/var/lib/neo4j/import
    entrypoint: >
      /bin/bash -c " set -e; echo '=== INITIALISATION DE LA BASE ==='; cypher-shell -a bolt://db:7687 -u neo4j -p connected_password -f /scripts/db_init.cypher; echo '=== TERMINÉ ==='; "
  # Backend
  backend:
    build: ./backend
    container_name: connected-backend
    ports:
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_URI: bolt://db:7687
      DB_USER: neo4j
      DB_PASSWORD: connected_password

  # frontend
  frontend:
    build: ./frontend
    container_name: connected-frontend
    ports:
      - "4200:80"

volumes:
  neo4j_data:
